### PR TITLE
feat(tracer): add support for capturing DynamoDB DocumentClient

### PR DESCRIPTION
**Pull request by dreamorosi**
## Description of your changes

Customer feedback ([link](https://dev.to/aws-builders/first-look-at-lambda-powertools-typescript-2k3p#tracer)) has pointed out a quirk of instrumenting a DynamoDB DocumentClient, in their words:

> One thing that isn't solved here (yet?) is the oddness of working with the X-Ray SDK and DynamoDB DocumentClient. When using DocumentClient with X-Ray, we need to do a workaround as the SDK needs access to the DocumentClient service property, but that's not exposed on the type. Here's how I've solved that problem in the past.

The new implementation attempts to instrument a client normally ([reference](https://github.com/aws/aws-sdk-js/blob/c578c8346494654914efb335779ca2620c3e6b36/lib/service.js#L177-L185)) first and then, if that fails, it tries to do so by accessing the `service` property. If both fail it throws as expected.

The advantage of this new mechanism (see example below) is that customers can instrument the `DocumentClient` in the same way as they do with other AWS SDK clients thus providing a more ergonomic API (& hopefully better DX).

### How to verify this change

**Before:**
```typescript
import DynamoDB, { DocumentClient } from 'aws-sdk/clients/dynamodb';
import { Tracer } from '@aws-lambda-powertools/tracer';

const tracer = new Tracer({ serviceName: 'paymentCollections' });
const client = new DocumentClient();
tracer.captureAWSClient((client as DocumentClient & { service: DynamoDB }).service); // Explicit typing required in userland
```

**After:**
```typescript
import { DocumentClient } from 'aws-sdk/clients/dynamodb';
import { Tracer } from '@aws-lambda-powertools/tracer';

const tracer = new Tracer({ serviceName: 'paymentCollections' });
const client = new DocumentClient();
tracer.captureAWSClient(client); // Like other AWS SDK v2 clients

// OR const client = tracer.captureAWSClient(new DocumentClient);
```

### Related issues, RFCs

N/A

### PR status

***Is this ready for review?:*** YES  
***Is it a breaking change?:*** NO

## Checklist

- [x] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] My changes generate *no new warnings*
- [x] The *code coverage* hasn't decreased
- [x] I have *added tests* that prove my change is effective and works
- [ ] New and existing *unit tests pass* locally and in Github Actions
- [x] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

N/A

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by flochaz — COMMENTED** [review]
Could we add an e2e test ?

**Comment by dreamorosi** [comment]
> Could we add an e2e test ?

Good idea, will do and come back to you

**Comment by dreamorosi** [comment]
Swapped STS calls for DynamoDB calls in all e2e tests for Tracer. Checks are now failing for unrelated reason, need to check why.

**Comment by flochaz** [comment]
you probably need to rebase first

**Comment by dreamorosi** [comment]
> you probably need to rebase first

You were right, that worked. Thanks a lot, now checks are passing!

**Review by ijemmy — APPROVED** [review]
Great DX improvement :) 

btw, I can't find this branch run in E2E workflow.  Normally this should be triggerred in "Approve" step but we don't have this for core maintainer.  

Is there a way for us to (manually?) run this before merging?

**Comment by flochaz** [comment]
> Great DX improvement :)
> 
> btw, I can't find this branch run in E2E workflow. Normally this should be triggerred in "Approve" step but we don't have this for core maintainer.
> 
> Is there a way for us to (manually?) run this before merging?

Screenshot 2022-01-25 at 10 47 40

**Comment by dreamorosi** [comment]
@flochaz @ijemmy ran the workflow, [passing result here](https://github.com/awslabs/aws-lambda-powertools-typescript/pull/450). 
In next PR, where applicable, I'll provide it as part of the checklist.

**Review by flochaz — APPROVED** [review]

**Pull request merged**
