### PR TITLE
fix(build): Update contributing.md and fix npm ci

### LINKED ISSUE #415: Docs: unable to clone & install for development
## Bug description

Reported by @michaelbrewer on the [Slack Dev channel](https://awsdevelopers.slack.com/archives/C01A6KK4UFK/p1641407918190900).

screen_shot_2022-01-05_at_10 45 22_am

Unable to install package after clean clone of repo, see screenshot above.

### Expected Behavior

Be able to `git clone ...` & `npm install`.

### Current Behavior

Throws an error for missing import of `@aws-lambda-powertools/commons` (see screenshot).

### Possible Solution

N/A

### Steps to Reproduce

1. `git clone`
2. `npm i`

### Environment

* **Powertools version used**: 0.2.0
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** N/A - local development
* **Debugging logs:**

```sh
npm --version
8.3.0
```

```sh
node --version
17.3.0
```

Running on Apple Silicon

### Related issues, RFCs

N/A

### PR DESCRIPTION
**Pull request by michaelbrewer**
## Description of your changes

fix(build): Update contributing.md and fix npm ci

Changes:
- Update CONTRIBUTING.md to use `npm ci`
- Fix `CONTRIBUTING.md` based on markdown lint recommended fixes
- Setup project references

closes #415

### How to verify this change

`git clean -fdx; npm ci`

### Related issues, RFCs

#415

### PR status

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

## Checklist

- [X] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [X] I have performed a *self-review* of my own code
- [X] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [X] I have made corresponding changes to the *documentation*
- [X] My changes generate *no new warnings*
- [X] The *code coverage* hasn't decreased
- [X] I have *added tests* that prove my change is effective and works
- [X] New and existing *unit tests pass* locally and in Github Actions
- [X] Any *dependent changes have been merged and published* in downstream module
- [X] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@dreamorosi would you have time to look at this ?

**Review by dreamorosi — COMMENTED** [review]
Apologies for the delay in the response.

We have been testing internally the issue and some preliminary results appear to show that `npm install` works with `npm v7.x` while `npm v8.x` throws the same error described in #415. We haven't settled yet on which version to use ([see discussion](https://github.com/awslabs/aws-lambda-powertools-typescript/discussions/331)) nor settled on how the local dev setup is going to look like (see [here](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/426) and [here](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/115)).

Regarding the changes to the `tsconfig.json` file I'd prefer having @flochaz have a look as he has been working on them more than me.

At this stage the only changes I'd feel comfortable approving are L58-L60 + L94 of `CONTRIBUTING.md`.

I'll request also a review from the other members to hear their opinion.

**Comment by michaelbrewer** [comment]
ok sure @dreamorosi i would have assume most people keep their `npm` version up to date now. But at least for now we should signal that `npm ci` will have less side effects

**Comment by michaelbrewer** [comment]
@flochaz  - is there something wrong with this PR?

**Review by flochaz — APPROVED** [review]
Nope, sorry for the late review.  LGTM

**Review by dreamorosi — APPROVED** [review]

**Pull request merged**
