### PR TITLE
feat(layers): add new regions

### PR DESCRIPTION
**Pull request by am29d**
## Description of your changes
I have added three new regions: 
* `eu-south-2`
* `eu-central-2`
* `ap-southeast-4`

in test and prod accounts. I have also bumped the layer version to the same level, current level 8. 

I had to fix the pre-push hook, otherwise I couldn't create the PR. 

### Related issues, RFCs

**Issue number:** #1169 

### PR status

***Is this ready for review?:*** NO  
***Is it a breaking change?:*** NO

## Checklist

- [x] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [ ] I have made corresponding changes to the *examples*
- [x] My changes generate *no new warnings*
- [x] The *code coverage* hasn't decreased
- [ ] I have *added tests* that prove my change is effective and works
- [x] New and existing *unit tests pass* locally and in Github Actions
- [x] Any *dependent changes have been merged and published*
- [x] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dreamorosi — COMMENTED** [review]
Thank you for the PR Alex, could you please also update the docs with the new ARNs (both versions & new regions)?

**Comment by dreamorosi** [comment]
Also could you please document under this PR the high level steps needed to onboard a new region, aside from the ones in the diff? I.e. CDK bootstrap the new region, etc.

This way next time if you are not available another maintainer can do it.

**Comment by am29d** [comment]
Added docs. Surprisingly, many regions undocumented existed before, so it does look like we added more regions.

**Review by dreamorosi — APPROVED** [review]
Thanks for working on this Alex, appreciate it!

And good spot for the missing regions!

**Pull request merged**
