### PR TITLE
fix(metrics): metadata and dimensions not cleared on publish

### PR DESCRIPTION
**Pull request by shdq**
## Description of your changes

To fix this bug, `clearDimensions();` and `clearMetadata();` are added to `publishStoredMetrics()` method to clear metadata and dimensions.

Bug described and reproduced in #1115.

### Related issues, RFCs

**Issue number:** #1115 

### PR status

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

## Checklist

- [x] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [ ] I have made corresponding changes to the *examples*
- [x] My changes generate *no new warnings*
- [x] The *code coverage* hasn't decreased
- [x] I have *added tests* that prove my change is effective and works
- [x] New and existing *unit tests pass* locally and in Github Actions
- [ ] Any *dependent changes have been merged and published* in downstream module
- [x] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by dreamorosi — APPROVED** [review]
Thank you for your contribution.

The changes seem appropriate to me and the automated checks are green.

I have requested a second review by one of the other maintainers before merging.

**Comment by shdq** [comment]
Thank you, Andrea @dreamorosi. If you need help with other issues, feel free to mention me.

**Review by flochaz — DISMISSED** [review]

**Comment by shdq** [comment]
Hello @flochaz, what is your doubt? Should I add more or fix existing tests?

**Comment by flochaz** [comment]
> Hello @flochaz, what is your doubt? Should I add more or fix existing tests?

Sorry got dragged on something else. Double checked and all good. approving. thx a lot for the work

**Review by flochaz — APPROVED** [review]

**Comment by dreamorosi** [comment]
Hi @shdq, the PR is merged and the change will be available in the next release. Congrats for getting your first PR merged in this project 🎉 

To answer your question, I would start with issues that have the `good-first-issue`, or consider [this one](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/751). If instead there's any other issue that interests you (except ones for Parameters & Idempotency which are already been worked on), feel free to comment under it & tag me and I'll be happy to give you more info.

**Pull request merged**
